spring:
  datasource:
    url: jdbc:h2:mem:bantads
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
